import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ButtonNavbar from "./components/ButtonNavbar";
import Dropdown from "./components/Dropdown";
import OptionDropdown from "./components/OptionDropdown";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav className="bg-slate-600 shadow-sm flex flex-row justify-between py-5 ">
                    <div className="flex flex-row ml-6">
                        <ButtonNavbar href="/">Home y icono</ButtonNavbar>
                    </div>
                    <div className="flex flex-row">
                        <Dropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                        </Dropdown>
                        <Dropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                            <OptionDropdown>option 1</OptionDropdown>
                        </Dropdown>
                    </div>
                    <div className="flex flex-row mr-6">
                        <ButtonNavbar href="/">Login</ButtonNavbar>
                        <ButtonNavbar href="/">Register</ButtonNavbar>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
